use slang_backend::bytecode::Chunk;
use slang_shared::DiagnosticEngine;

/// A composable compilation pipeline providing error recovery capabilities
///
/// The CompilationPipeline implements a multi-stage compilation process that can
/// gracefully handle errors and continue processing when possible. It integrates
/// with the DiagnosticEngine to provide rich error reporting and supports both
/// fail-fast and error recovery modes.
///
/// ### Features
/// - Stage-by-stage compilation with clear error boundaries
/// - Error recovery mode for collecting multiple errors in one pass
/// - Rich diagnostic reporting with source context
/// - Composable pipeline stages that can be chained or used independently
/// - Integration with all compiler phases: lexing, parsing, semantic analysis, codegen
///
/// ### Example Usage
/// ```rust
/// use slang_compilation_pipeline::CompilationPipeline;
///
/// let source = "let x = 42;";
/// let result = CompilationPipeline::new(source, Some("example.sl".to_string()), true)
///     .execute_all_stages();
/// ```
pub struct CompilationPipeline<'a> {
    /// The source code being compiled
    source: &'a str,
    /// Optional file name for better error reporting
    file_name: Option<String>,
    /// Whether to enable error recovery mode
    recovery: bool,
}

impl<'a> CompilationPipeline<'a> {
    /// Creates a new compilation pipeline with the given source code
    ///
    /// This initializes a fresh compilation pipeline with default settings.
    /// The diagnostic engine is automatically configured with the provided
    /// file name and source text for better error reporting.
    ///
    /// ### Arguments
    /// * `source` - The source code to compile
    /// * `file_name` - Optional file name for error reporting context
    ///
    /// ### Returns
    /// A new CompilationPipeline ready for processing
    ///
    /// ### Example
    /// ```rust
    /// use slang_compilation_pipeline::CompilationPipeline;
    /// let pipeline = CompilationPipeline::new(
    ///     "let x = 42;",
    ///     Some("example.sl".to_string()),
    ///     false
    /// );
    /// ```
    pub fn new(source: &'a str, file_name: Option<String>, recovery: bool) -> Self {
        Self {
            source,
            file_name,
            recovery,
        }
    }

    /// Extract the diagnostic engine from the pipeline
    /// 
    /// This method returns a new diagnostic engine since the pipeline
    /// no longer stores one internally. The returned engine will be
    /// empty and should only be used for compatibility purposes.
    pub fn into_diagnostics(self) -> DiagnosticEngine<'a> {
        DiagnosticEngine::new()
    }

    /// Execute all compilation stages
    ///
    /// This is the primary method for compiling Slang source code. It executes
    /// all compilation stages in sequence and returns the final result.
    ///
    /// The method performs the following stages:
    /// 1. **Tokenization**: Convert source text into tokens
    /// 2. **Parsing**: Build an Abstract Syntax Tree (AST) from tokens  
    /// 3. **Semantic Analysis**: Validate types, scopes, and semantic rules
    /// 4. **Code Generation**: Generate executable bytecode
    ///
    /// Each stage can optionally print debug information if the corresponding
    /// feature flags are enabled (`print-tokens`, `print-ast`, `print-byte_code`).
    ///
    /// ### Error Handling
    /// The pipeline supports both fail-fast and recovery modes:
    /// - **Fail-fast mode** (default): Stops at the first error
    /// - **Recovery mode**: Attempts to continue compilation after errors
    ///
    /// ### Returns
    /// A `CompilationResult` containing either:
    /// - `Success`: Generated bytecode and diagnostic information
    /// - `Failed`: Diagnostic information about compilation errors
    pub fn execute_all_stages(self) -> CompilationResult<'a> {
        use crate::pipeline::builder::PipelineBuilder;
        use crate::pipeline::stages::*;
        use crate::pipeline::error::ErrorStrategy;

        // Create pipeline with the new architecture
        let mut pipeline = PipelineBuilder::new(self.source)
            .add_stage(TokenizationStage)
            .add_stage(ParsingStage)  
            .add_stage(SemanticAnalysisStage)
            .add_stage(CodeGenerationStage);

        // Configure error strategy based on recovery mode
        if self.recovery {
            pipeline = pipeline.with_error_strategy(ErrorStrategy::Recover { continue_on_non_critical: true });
        }

        // Set file name if available
        let pipeline = match self.file_name {
            Some(name) => pipeline.with_file_name(name),
            None => pipeline,
        };

        // Build and execute the pipeline
        let pipeline_result = pipeline.build().execute();
        
        // Convert pipeline result to compilation result
        match pipeline_result {
            crate::pipeline::result::CompilationResult::Success { output, diagnostics } => {
                // Try to downcast the output to Chunk
                match output.downcast::<slang_backend::bytecode::Chunk>() {
                    Ok(chunk) => CompilationResult::Success {
                        chunk: *chunk,
                        diagnostics,
                    },
                    Err(_) => {
                        // This shouldn't happen if the pipeline is set up correctly
                        CompilationResult::Failed { diagnostics }
                    }
                }
            }
            crate::pipeline::result::CompilationResult::Failed { diagnostics } => {
                CompilationResult::Failed { diagnostics }
            }
        }
    }
}

/// Represents a stage in the compilation pipeline
///
/// Each compilation stage can either succeed and produce data for the next stage,
/// The final result of compilation
///
/// This enum represents the ultimate outcome of the entire compilation process,
/// containing either successful bytecode generation or failure information with
/// comprehensive diagnostics.
///
/// ## Variants
/// - `Success`: Compilation completed successfully with executable bytecode
/// - `Failed`: Compilation failed with diagnostic information for error reporting
pub enum CompilationResult<'a> {
    /// Compilation succeeded with executable bytecode
    Success {
        /// The generated bytecode chunk ready for execution
        chunk: Chunk,
        /// The diagnostic engine containing any warnings or notes
        diagnostics: DiagnosticEngine<'a>,
    },
    /// Compilation failed with error information
    Failed {
        /// The diagnostic engine containing all errors, warnings, and notes
        diagnostics: DiagnosticEngine<'a>,
    },
}
