//! # Slang Compilation Pipeline
//!
//! This crate provides the compilation pipeline infrastructure for the Slang programming language.
//! It implements a composable, multi-stage compilation process with error recovery capabilities
//! and rich diagnostic reporting.
//!
//! ## Features
//!
//! - **Composable Pipeline Architecture**: Chain compilation stages together with clear boundaries
//! - **Error Recovery**: Continue compilation after errors to collect multiple issues in one pass
//! - **Rich Diagnostics**: Comprehensive error reporting with source context
//! - **Debug Features**: Optional printing of tokens, AST, and bytecode during compilation
//! - **Stage Isolation**: Each compilation stage is isolated with proper error handling
//!
//! ## Architecture
//!
//! The compilation pipeline consists of several key components:
//!
//! - **ChainPipeline**: Type-safe pipeline with compile-time observer validation
//! - **ExecutionChain**: Predefined compilation stage sequences
//! - **CompilationStage**: Trait for implementing individual compilation stages
//! - **StageObserver**: Interface for monitoring compilation progress and debugging
//! - **DiagnosticEngine Integration**: Direct error reporting from each stage
//!
//! ## Usage
//!
//! ```rust
//! use slang_compilation_pipeline::{ChainPipeline, CompilationResult};
//! use slang_compilation_pipeline::pipeline::execution_chain::FullCompilationChain;
//!
//! let source = "let x = 42;";
//! let result = ChainPipeline::full_compilation(&source)
//!     .compile_to_bytecode();
//!
//! match result {
//!     CompilationResult::Success { output, diagnostics } => {
//!         // Use the generated bytecode
//!         println!("Compilation successful!");
//!     }
//!     CompilationResult::Failed { diagnostics } => {
//!         // Handle compilation errors
//!         eprintln!("Compilation failed");
//!     }
//! }
//! ```

pub mod pipeline;


// New preferred API - Type-safe pipeline with compile-time observer validation
pub use pipeline::typed_builder::{
    ChainPipeline, TokenizationPipeline, ParsingPipeline, 
    ASTPipeline, FullCompilationPipeline,
    HasStage, TokenizationStageMarker, ParsingStageMarker, 
    SemanticStageMarker, CodegenStageMarker,
};

// Supporting API
pub use pipeline::{
    execution_chain::{TokenizationChain, ParsingChain, ASTChain, FullCompilationChain},
    stage::{CompilationStage, StageContext},
    observers::{StageObserver, ObserverRegistry, TokenizationObserver, ParsingObserver, SemanticObserver, CodegenObserver},
    error::{ErrorStrategy, PipelineError, RecoveryAction},
    result::CompilationResult,
    stages::{TokenizationStage, ParsingStage, SemanticAnalysisStage, CodeGenerationStage},
};
