//! # Slang Compilation Pipeline
//!
//! This crate provides the compilation pipeline infrastructure for the Slang programming language.
//! It implements a composable, multi-stage compilation process with error recovery capabilities
//! and rich diagnostic reporting.
//!
//! ## Features
//!
//! - **Composable Pipeline Architecture**: Chain compilation stages together with clear boundaries
//! - **Error Recovery**: Continue compilation after errors to collect multiple issues in one pass
//! - **Rich Diagnostics**: Comprehensive error reporting with source context
//! - **Debug Features**: Optional printing of tokens, AST, and bytecode during compilation
//! - **Stage Isolation**: Each compilation stage is isolated with proper error handling
//!
//! ## Architecture
//!
//! The compilation pipeline consists of several key components:
//!
//! - **CompilationPipeline**: Main facade for executing compilation
//! - **PipelineBuilder**: Fluent API for constructing pipelines with custom configurations
//! - **CompilationStage**: Trait for implementing individual compilation stages
//! - **StageObserver**: Interface for monitoring compilation progress and debugging
//! - **DiagnosticEngine Integration**: Direct error reporting from each stage
//!
//! ## Usage
//!
//! ```rust
//! use slang_compilation_pipeline::{CompilationPipeline, CompilationResult};
//!
//! let source = "let x = 42;";
//! let result = CompilationPipeline::new(source, Some("example.sl".to_string()), false)
//!     .execute_all_stages();
//!
//! match result {
//!     CompilationResult::Success { chunk, diagnostics } => {
//!         // Use the generated bytecode
//!         println!("Compilation successful!");
//!     }
//!     CompilationResult::Failed { diagnostics } => {
//!         // Handle compilation errors
//!         eprintln!("Compilation failed");
//!     }
//! }
//! ```

pub mod pipeline;
pub mod compilation_pipeline;

// Re-export main public API
pub use compilation_pipeline::{CompilationPipeline, CompilationResult};
pub use pipeline::{
    builder::PipelineBuilder,
    stage::{CompilationStage, StageContext},
    observers::{StageObserver, ObserverRegistry, TokenizationObserver, ParsingObserver, SemanticObserver, CodegenObserver},
    error::{ErrorStrategy, PipelineError, RecoveryAction},
    result::CompilationResult as PipelineCompilationResult,
    stages::{TokenizationStage, ParsingStage, SemanticAnalysisStage, CodeGenerationStage},
};
