//! # Slang Compilation Pipeline
//!
//! This crate provides the compilation pipeline infrastructure for the Slang programming language.
//! It implements a composable, multi-stage compilation process with error recovery capabilities
//! and rich diagnostic reporting.
//!
//! ## Features
//!
//! - **Composable Pipeline Architecture**: Chain compilation stages together with clear boundaries
//! - **Error Recovery**: Continue compilation after errors to collect multiple issues in one pass
//! - **Rich Diagnostics**: Comprehensive error reporting with source context
//! - **Debug Features**: Optional printing of tokens, AST, and bytecode during compilation
//! - **Stage Isolation**: Each compilation stage is isolated with proper error handling
//!
//! ## Architecture
//!
//! The compilation pipeline consists of several key components:
//!
//! - **ChainPipeline**: Type-safe pipeline with compile-time observer validation
//! - **ExecutionChain**: Predefined compilation stage sequences
//! - **CompilationStage**: Trait for implementing individual compilation stages
//! - **StageObserver**: Interface for monitoring compilation progress and debugging
//! - **DiagnosticEngine Integration**: Direct error reporting from each stage
//!
//! ## Usage
//!
//! ```rust
//! use slang_compilation_pipeline::{ChainPipeline, CompilationResult, SlangSourceFile};
//! use slang_compilation_pipeline::execution_chain::FullCompilationChain;
//!
//! let source_file = SlangSourceFile::new("example.sl", "let x = 42;".to_string()).unwrap();
//! let result = ChainPipeline::full_compilation()
//!     .execute(source_file);
//!
//! match result {
//!     CompilationResult::Success { output, diagnostics } => {
//!         // Use the generated bytecode
//!         println!("Compilation successful!");
//!     }
//!     CompilationResult::Failed { diagnostics } => {
//!         // Handle compilation errors
//!         eprintln!("Compilation failed");
//!     }
//! }
//! ```

pub mod source_file;
// Core traits and types for the new pipeline architecture
pub mod error;
pub mod observer;
pub mod result;
pub mod stage;
pub mod stages;

// Type-safe HList-based pipeline implementation
pub mod hlist;

// Macros for defining execution chain types and constructors
pub mod chain_macros;

// New hybrid pattern: execution chain + true builder
pub mod execution_chain;

// Chain-aware typed pipeline for compile-time observer validation
pub mod chain_pipeline;

// Re-export key types for convenient access
pub use hlist::{Execute, HCons, HList, HList1, HList2, HList3, HList4, HList5, HNil};

// Re-export new hybrid pattern types
pub use execution_chain::{ExecuteChain, ExecutionChain};

// Re-export typed builder components
pub use chain_pipeline::{
    ASTPipeline, ChainPipeline, FullCompilationPipeline, ParsingPipeline, TokenizationPipeline,
};

// Export the source file type
pub use source_file::{SlangSourceFile, SourceFileError};

// Supporting API
pub use {
    error::ErrorStrategy,
    execution_chain::{ASTChain, FullCompilationChain, ParsingChain, TokenizationChain},
    observer::{
        CodegenObserver, ObserverRegistry, ParsingObserver, SemanticObserver, StageObserver,
        TokenizationObserver,
    },
    result::CompilationResult,
    stage::{CompilationStage, StageContext},
    stages::{CodeGenerationStage, ParsingStage, SemanticAnalysisStage, TokenizationStage},
};
