[package]
name = "slang"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"

[workspace]
members = [
        "crate/frontend",
        "crate/ir",
        "crate/backend",
        "crate/types",
        "crate/derive",
        "crate/shared",
        "crate/error",
        "crate/compilation_pipeline",
]

[workspace.dependencies]
slang_compilation_pipeline = { path = "crate/compilation_pipeline", features = [] }
[features]
default = []
print-byte_code = ["slang_backend/print-byte_code"]
print-ast = ["slang_ir/print-ast"]
trace-execution = ["slang_backend/trace-execution"]

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
colored = "2.0.4"
slang_backend = { path = "crate/backend", features = [] }
slang_compilation_pipeline = { path = "crate/compilation_pipeline", features = [] }
slang_error = { path = "crate/error", features = [] }
slang_frontend = { path = "crate/frontend", features = [] }
slang_ir = { path = "crate/ir", features = [] }
slang_shared = { path = "crate/shared", features = [] }
slang_types = { path = "crate/types", features = [] }
zip = "0.6"


[dev-dependencies]
# E2E tests
assert_cmd = "2.0.12"
predicates = "3.0.4"
tempfile = "3.8.1"
rstest = "0.18.2"
# Performance tests
divan = "0.1.21"
peak_alloc = "0.2"


[[bench]]
name = "lexer_benchmarks"
harness = false

[[bench]]
name = "parser_benchmarks"
harness = false

[[bench]]
name = "semantic_benchmarks"
harness = false

[[bench]]
name = "codegen_benchmarks"
harness = false

[[bench]]
name = "vm_benchmarks"
harness = false

[[bench]]
name = "e2e_benchmarks"
harness = false
