[package]
name = "slang_backend"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"
description = "Backend compilation and execution engine of the Slang programming language"
authors = ["Frederik Tobner <f.tobner@gmail.com>"]

[dependencies]
slang_ir = { path = "../ir" }
slang_derive = { path = "../derive" }
slang_error = { path = "../error" }

[features]
default = []
trace-execution = []

[lib]
name = "slang_backend"
path = "src/lib.rs"
