[package]
name = "slang_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
slang_ir = { path = "../ir" }
slang_frontend = { path = "../frontend" }

[features]
default = []
trace-execution = []

[lib]
name = "slang_backend"
path = "src/lib.rs"