[package]
name = "slang_ir"
version = "0.1.0"
edition = "2024"

[dependencies]
slang_types = { path = "../types" }

[features]
default = []
print-ast = []


[lib]
name = "slang_ir"
path = "src/lib.rs"

