use crate::pipeline::observers::StageObserver;
use slang_ir::ast::Statement;
use slang_backend::bytecode::Chunk;
use slang_frontend::Token;
use colored::Colorize;

/// Observer that prints AST when parsing or semantic analysis completes
pub struct ASTPrintObserver {
    enabled: bool,
}

impl ASTPrintObserver {
    pub fn new() -> Self {
        Self { enabled: true }
    }

    pub fn disabled() -> Self {
        Self { enabled: false }
    }

    fn print_ast(&self, statements: &Vec<Statement>) {
        if !self.enabled {
            return;
        }

        println!("{}", "=== AST ===".bright_green().bold());
        #[cfg(feature = "print-ast")]
        {
            use slang_ir::ast_printer::ASTPrinter;
            let mut printer = ASTPrinter::new();
            if let Err(e) = printer.print(statements) {
                eprintln!("Warning: Failed to print AST: {}", e);
            }
        }
        #[cfg(not(feature = "print-ast"))]
        {
            println!("AST printing not available (print-ast feature disabled)");
            println!("Found {} statements", statements.len());
        }
        println!("{}", "=== END AST ===".bright_green().bold());
    }
}

impl Default for ASTPrintObserver {
    fn default() -> Self {
        Self::new()
    }
}

// Implementation for parsing stage (tokens -> AST)
impl StageObserver<Vec<Token>, Vec<Statement>> for ASTPrintObserver {
    fn on_stage_success(&self, output: &Vec<Statement>) {
        self.print_ast(output);
    }
}

// Implementation for semantic analysis stage (AST -> AST)
impl StageObserver<Vec<Statement>, Vec<Statement>> for ASTPrintObserver {
    fn on_stage_success(&self, output: &Vec<Statement>) {
        self.print_ast(output);
    }
}

/// Observer that prints bytecode when code generation completes
pub struct BytecodePrintObserver {
    enabled: bool,
    show_line_numbers: bool,
}

impl BytecodePrintObserver {
    pub fn new() -> Self {
        Self { 
            enabled: true,
            show_line_numbers: true,
        }
    }

    pub fn disabled() -> Self {
        Self { 
            enabled: false,
            show_line_numbers: false,
        }
    }

    pub fn with_line_numbers(mut self, show: bool) -> Self {
        self.show_line_numbers = show;
        self
    }
}

impl Default for BytecodePrintObserver {
    fn default() -> Self {
        Self::new()
    }
}

impl StageObserver<Vec<Statement>, Chunk> for BytecodePrintObserver {
    fn on_stage_success(&self, output: &Chunk) {
        if !self.enabled {
            return;
        }

        println!("{}", "=== BYTECODE ===".bright_yellow().bold());
        #[cfg(feature = "print-byte_code")]
        {
            use slang_backend::bytecode::disassembler::Disassembler;
            let disassembler = Disassembler::new(output);
            if let Err(e) = disassembler.disassemble() {
                eprintln!("Warning: Failed to disassemble bytecode: {}", e);
            }
        }
        #[cfg(not(feature = "print-byte_code"))]
        {
            println!("Bytecode printing not available (print-byte_code feature disabled)");
            println!("Generated bytecode chunk with {} instructions", output.code.len());
        }
        println!("{}", "=== END BYTECODE ===".bright_yellow().bold());
    }
}
