[package]
name = "slang_shared"
version = "0.1.0"
edition = "2024"

[features]
default = []

[lib]
name = "slang_shared"
path = "src/lib.rs"

[dependencies]
slang_types = { path = "../types" }
slang_error = { path = "../error" }
slang_ir = { path = "../ir" }
colored = "2.0.4"

