use slang_compilation_pipeline::pipeline::observers::StageObserver;
use slang_ir::ast::Statement;
use slang_backend::bytecode::Chunk;
use colored::Colorize;

/// Observer that prints bytecode when code generation completes
/// This observer is primarily used for debugging and development purposes
pub struct BytecodePrintObserver {
}

impl BytecodePrintObserver {
    pub fn new() -> Self {
        Self { 
        }
    }
}

impl Default for BytecodePrintObserver {
    fn default() -> Self {
        Self::new()
    }
}

impl StageObserver<Vec<Statement>, Chunk> for BytecodePrintObserver {
    fn on_stage_success(&self, output: &Chunk) {

        println!("{}", "=== BYTECODE ===".bright_yellow().bold());
        println!("Generated bytecode chunk with {} instructions", output.code.len());
        println!("Constants: {}", output.constants.len());
        println!("Identifiers: {}", output.identifiers.len());
        println!("{}", "=== END BYTECODE ===".bright_yellow().bold());
    }
}
