use colored::Colorize;
use slang_backend::bytecode::Chunk;
use slang_compilation_pipeline::observer::StageObserver;
use slang_ir::ast::Statement;

/// Observer that prints bytecode when code generation completes
/// This observer is primarily used for debugging and development purposes
pub struct BytecodePrinter {}

impl BytecodePrinter {
    pub fn new() -> Self {
        Self {}
    }
}

impl Default for BytecodePrinter {
    fn default() -> Self {
        Self::new()
    }
}

impl StageObserver<Vec<Statement>, Chunk> for BytecodePrinter {
    fn on_stage_success(&self, output: &Chunk) {
        println!("{}", "=== BYTECODE ===".bright_yellow().bold());
        println!(
            "Generated bytecode chunk with {} instructions",
            output.code.len()
        );
        println!("Constants: {}", output.constants.len());
        println!("Identifiers: {}", output.identifiers.len());
        println!("{}", "=== END BYTECODE ===".bright_yellow().bold());
    }
}
